# Generated by Django 3.2.2 on 2021-05-14 12:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('3cf88fe0-9823-4893-aa8d-25df809356d3'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_blacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_blacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('Id', models.CharField(default=uuid.UUID('36afee76-3b3e-4af6-ac7e-af6f486f897d'), max_length=50, primary_key=True, serialize=False)),
                ('permit', models.CharField(default='UAX', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FleetManager',
            fields=[
                ('Id', models.CharField(default=uuid.UUID('6fd3aa17-d0b3-4355-8c78-a411a381d187'), max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('a313ad9e-374b-4062-912e-2d458785c849'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='organisationx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisation_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisation_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('Id', models.CharField(default=uuid.UUID('5062027e-9727-475b-9d36-a560efca6dca'), max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Id', models.CharField(default=uuid.UUID('8e88fd80-dddb-46ec-8d0c-9353ed1d2660'), max_length=50, primary_key=True, serialize=False)),
                ('type_of_vehicle', models.CharField(default='range_rover', max_length=50)),
                ('brand', models.CharField(default='range_rover', max_length=50)),
                ('carrying_capacity', models.CharField(default='range_rover', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('defaultuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.defaultuser')),
                ('Id', models.CharField(default=uuid.UUID('8aa0cede-2742-46e2-8e61-29834e80d24e'), max_length=50, primary_key=True, serialize=False)),
                ('primary_contact', phonenumber_field.modelfields.PhoneNumberField(default='+256777777', max_length=128, region=None)),
                ('secondary_contact', phonenumber_field.modelfields.PhoneNumberField(default='+256777777', max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('api.defaultuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('4e4f4ed7-5df1-43e7-9c6f-f19b0f27d301'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_blacklists', to='api.blacklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_vehicleblacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_vehicleblacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='api.vehicle')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7daf7d18-e808-41ba-80f0-f5d63a71ee96'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Stationx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_station_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_station_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Station_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7edb7cf6-1a2e-477b-a866-70a349a7e374'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='projectx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_project_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_project_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('38b77b6b-7e0f-4321-9941-b6ca0f7de9fa'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blacklists', to='api.blacklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_passengerblacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_passengerblacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Passengers', to='api.passenger')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationVehicle',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('a68459c7-0274-43b5-b23f-e79ef41a6aae'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationvehicle_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationvehicle_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisation_vehicle', to='api.organisation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.vehicle')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationFleetManager',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('93a68c25-9ab2-4747-9eab-99eaec57da2b'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationfleetmanager_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('fleet_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_managers', to='api.fleetmanager')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationfleetmanager_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationDriver',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('206e0524-6b3f-47f3-9266-e186e96a8363'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationdriver_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.driver')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationdriver_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisation_driver', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('1675a8f4-a12c-470d-9f81-3fcb5cb7d6e0'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver_blacklists', to='api.blacklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_driverblacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drivers', to='api.driver')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_driverblacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7848628b-13b1-417f-852e-f995cd81ab8a'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='directoratex', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_directorate_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_directorate_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Directorate_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7d818005-5885-4967-841a-a32e2ffc6982'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='departmentx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_department_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_department_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('75cfa9e3-f004-4a91-8f27-40cc866ae324'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='branchx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_branch_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_branch_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Branch_organisations', to='api.organisation')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blacklist',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blacklist_organisations', to='api.organisation'),
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('Id', models.CharField(default=uuid.UUID('adc726de-082b-4c7d-905f-7270ba99bc36'), max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SysAdmin', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Passenger', to='api.user'),
        ),
        migrations.AddField(
            model_name='fleetmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FleetManager', to='api.user'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to='api.user'),
        ),
    ]
