# Generated by Django 3.2.4 on 2021-06-21 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('c2caec5d-0e73-412d-9ccd-6ad8bb7d379a'), max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('8c487ea6-9216-4796-9703-81d5da447e00'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='branchx', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('4d3c129e-25d4-465b-a206-ae381ed710c5'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='departmentx', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('c3f583b6-fc36-49f4-8905-46e305a2eb55'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='directoratex', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorateDepartment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('fe82f5d1-53f1-4f54-be24-f77670556f80'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='directoratex', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('abaff9ec-3a9d-42f0-9fd5-c43562ea3935'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverTrip',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('51d6a802-f59d-4f42-80bd-820a984530aa'), max_length=50, primary_key=True, serialize=False)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('destination', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FleetManagerTrip',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('47f2e1c2-995e-41f7-b6b9-5d0ad351f1e9'), max_length=50, primary_key=True, serialize=False)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('destination', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('162c76bd-b9cb-467c-af4a-e4881e91a5f0'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='organisationx', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationDriver',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('df017c57-0a6f-48f1-be74-bc21dcfbe713'), max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationFleetManager',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('c009aad6-5157-4ae4-8f74-93c0c6e60c21'), max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationVehicle',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('cb7395d3-5940-441e-98b9-0f072e76d037'), max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('3ba3a736-a00f-4106-b1e5-a36fc7c44c0a'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerTrip',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('fc41028d-375e-4427-ac51-856dffcdd74f'), max_length=50, primary_key=True, serialize=False)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('destination', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('d6fbba59-7b39-471d-bfb7-2558b5fd73f9'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='projectx', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectVehicleDeploy',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('29b96ee8-1aa0-4d86-a59a-8ce80e7ce2a5'), max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('a2b6e6bd-78b4-4e02-a2b8-1af6f1f073a1'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='projectx', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('1d0ca1f5-2bae-4b89-b5ec-7755fe0a913d'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Stationx', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationVehicleDeploy',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('6d176d9d-261b-4178-8eaf-acb16bc1f52b'), max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('19353ba7-efa2-438e-ae3a-86dc203da4ac'), max_length=50, primary_key=True, serialize=False)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('destination', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7a2ac0b3-12ec-489f-8f64-922a1a341358'), max_length=50, primary_key=True, serialize=False)),
                ('type_of_vehicle', models.CharField(default='Double Cabin', max_length=50)),
                ('brand', models.CharField(default='Toyota', max_length=50)),
                ('carrying_capacity', models.CharField(default='4', max_length=50)),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('42bbd431-f92d-4d75-8ee6-416f96c7d5c3'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blacklist')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
    ]
