# Generated by Django 3.2.2 on 2021-05-11 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('8ad6626b-634c-4fe2-bfe1-82d239d59bfe'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_blacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_blacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('eaa566f8-47a5-44d8-8487-89f8de4ecf17'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='organisationx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisation_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisation_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Id', models.CharField(default=uuid.UUID('e9b00212-c728-4a64-9749-a22998f19247'), max_length=50, primary_key=True, serialize=False)),
                ('type_of_vehicle', models.CharField(default='range_rover', max_length=50)),
                ('brand', models.CharField(default='range_rover', max_length=50)),
                ('carrying_capacity', models.CharField(default='range_rover', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='permit',
            field=models.CharField(default='UAX', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+256777777', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+256777777', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Id',
            field=models.CharField(default=uuid.UUID('d98c9bef-72ac-4f26-90fe-6b5af536f1cd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='Id',
            field=models.CharField(default=uuid.UUID('6762ef62-c8e6-4226-beef-90a9e42cb3ab'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Id',
            field=models.CharField(default=uuid.UUID('ad91a0fb-f700-4eb4-9fb3-706d6d75245a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='Id',
            field=models.CharField(default=uuid.UUID('09eb5661-456a-4fbb-a56a-8f42dd4788b2'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('0416810a-0495-4827-850f-5e21ed772e67'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VehicleBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7a9d174d-4bc5-4eaf-87ff-9876f961b284'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_blacklists', to='api.blacklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_vehicleblacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_vehicleblacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='api.vehicle')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('418fca54-aef3-4574-b693-c5a180742ffb'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Stationx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_station_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_station_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Station_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('638cbcc2-a7c0-495a-8793-5fcbcfc6e461'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='projectx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_project_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_project_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('8b65b7ad-3b51-4e26-a674-ad2fa4d6e924'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blacklists', to='api.blacklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_passengerblacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_passengerblacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Passengers', to='api.passenger')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationVehicle',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('d61a86f9-7e98-423f-b4d8-96637f4bc7cb'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationvehicle_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationvehicle_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisation_vehicle', to='api.organisation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.vehicle')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationFleetManager',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('3438665a-85a5-46e7-85c7-0c60f180b5f3'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationfleetmanager_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('fleet_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_managers', to='api.fleetmanager')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationfleetmanager_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationDriver',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('64cca598-2939-416c-b4c8-c5fd4042492b'), max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationdriver_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.driver')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_organisationdriver_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisation_driver', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverBlacklist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('96ba843b-e359-47e3-b689-0028fc694611'), max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver_blacklists', to='api.blacklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_driverblacklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drivers', to='api.driver')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_driverblacklist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7bb6c56e-e34c-43f4-95d6-6b5285cfd4a1'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='directoratex', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_directorate_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_directorate_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Directorate_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('7cfc2b64-0939-4aba-8815-466e2c80618a'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='departmentx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_department_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_department_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.UUID('e0281e82-2245-4b93-a0e4-d5f2313169ee'), max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='branchx', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_branch_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_branch_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Branch_organisations', to='api.organisation')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blacklist',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blacklist_organisations', to='api.organisation'),
        ),
    ]
