# Generated by Django 3.2.2 on 2021-05-14 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('0aa2576f-d6ee-4e8d-90fa-6ce741f30d61'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=uuid.UUID('9ef62aaa-8f45-41d9-946b-4a4b02f208a5'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('a043b016-1cf7-4f97-a89c-570b118bb314'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='id',
            field=models.CharField(default=uuid.UUID('c71576be-b5bb-4061-a862-795ed46734b2'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Id',
            field=models.CharField(default=uuid.UUID('5e9dc358-d6c4-4aab-9347-6e5c5532e27e'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('1cc8cc1a-312a-479b-89a3-1daa3258d0ed'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='Id',
            field=models.CharField(default=uuid.UUID('dc611491-ff9c-4d37-9c75-3714bd258995'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=uuid.UUID('1452e477-a400-47ac-96fe-b467f7fadd92'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationdriver',
            name='id',
            field=models.CharField(default=uuid.UUID('36a5d807-8b69-4ec3-8d74-062a75e895df'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationfleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('f5d790c4-a937-42a0-906f-96017a93a431'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('ea3c3b46-2a5f-4574-bc5a-7cbeaed651ad'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Id',
            field=models.CharField(default=uuid.UUID('cd5c149c-6403-4cfe-9673-8febcf1a5b95'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('ed08d840-1859-4041-96bb-fd3db911fdc5'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('f847d589-83c6-4888-a2b3-f2cb2bc74b29'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.CharField(default=uuid.UUID('9e4376f0-7549-44fc-ad79-77e52943b33d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='Id',
            field=models.CharField(default=uuid.UUID('19195556-39dd-412d-880d-635da8d3e9ab'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('895186d7-fedd-468a-b8df-4db19c67237a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Id',
            field=models.CharField(default=uuid.UUID('7a6bd405-0eac-4a96-b9be-03a903a5919a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('da1db71e-8024-42bd-adbb-d5717525663d'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
