# Generated by Django 3.2.2 on 2021-05-14 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210511_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('932eb704-4733-446f-a6ad-c8720c9a0ae9'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=uuid.UUID('221b68f2-d208-4b8d-bcf3-5c45fea40d26'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('6a3ab209-f11a-42fc-a21f-00fc41e559e5'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='id',
            field=models.CharField(default=uuid.UUID('f1535e1d-d134-4d83-a566-3225b12b5dcc'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Id',
            field=models.CharField(default=uuid.UUID('370884ad-4f39-455f-8ccb-c932ed0c04c8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('99ef296c-f0d3-43db-a737-c61ce03a51df'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='Id',
            field=models.CharField(default=uuid.UUID('bf0e05f0-2423-4e17-b63c-13ce4ddbf00d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=uuid.UUID('16bad895-9ead-4771-849c-8fa62d87c0e8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationdriver',
            name='id',
            field=models.CharField(default=uuid.UUID('f649ef3d-c47e-45a1-868b-b9cd99a2b11d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationfleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('d7c59244-750a-4af9-9c0d-c86f16dce07a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('0100afe2-3363-4bf9-ae32-fad536f384b1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Id',
            field=models.CharField(default=uuid.UUID('2d3df95d-dfa0-4135-ba37-f90739ca934b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('dbc1a39b-54c7-4b8e-b2d3-1f42d7a6f9f6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('0aae229a-e24c-4e39-bb07-d64e4ff56b4e'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.CharField(default=uuid.UUID('aa3d66b8-5480-4ace-8965-43ae6e960800'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='Id',
            field=models.CharField(default=uuid.UUID('0015981d-8c6a-4d93-a3d6-9bd3cf094477'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('a7254b99-e29e-4228-9bda-15fb300cfc48'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Id',
            field=models.CharField(default=uuid.UUID('61e9660b-0d32-49d5-802f-189fcee7780b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('cc6c365e-f9c2-4b6d-9902-11e289c761b5'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
