# Generated by Django 3.2.2 on 2021-05-14 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210514_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('e5dd4504-5cec-46b3-9530-621caab04567'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=uuid.UUID('2be1606a-a915-4139-a01e-c14df859ed14'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('0ac68bef-e92d-4482-a026-c39b637521ab'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='id',
            field=models.CharField(default=uuid.UUID('cabb5e91-95b1-4c48-b879-a87a708eda76'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Id',
            field=models.CharField(default=uuid.UUID('91b03371-d78f-4e5e-9843-82ebaa5faf01'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('9a7abb21-d7a6-43d4-be0d-f7ae0faed9a2'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='Id',
            field=models.CharField(default=uuid.UUID('3e387150-e3e1-4f77-83d1-131cdc28c381'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=uuid.UUID('cafde3e4-c816-4890-9a44-55064d22117b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationdriver',
            name='id',
            field=models.CharField(default=uuid.UUID('483d09c7-e934-4349-bdfc-96d1cdc90aaa'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationfleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('a96a50d8-7c11-4110-9faa-d1233cc43e63'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('606cbf78-cea4-45ef-8bf2-2e089b88c8e4'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Id',
            field=models.CharField(default=uuid.UUID('4ce74355-7271-4eac-a17d-f0887dbc30d6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('72d94ab5-4e39-4642-9d44-3b6b0ca95980'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('13b70d90-94a7-4e4b-9b75-0991b9351028'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.CharField(default=uuid.UUID('c4b96710-9165-4ad2-9153-ee7a13548f54'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='Id',
            field=models.CharField(default=uuid.UUID('5afeb0fe-b57e-4aa2-bf7d-3bcda5edc700'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('8e083ed4-7c56-44f8-90c1-2e3a9a2408f0'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Id',
            field=models.CharField(default=uuid.UUID('735120c9-93a5-4ef9-8a57-8ef68c470815'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('e4724d22-b9ca-46c4-839a-929d067e8e3d'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
