# Generated by Django 3.2.4 on 2021-08-15 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210803_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetmanagertrip',
            name='time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
