# Generated by Django 3.2.2 on 2021-05-14 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210514_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('effaab2a-07ff-4e3a-b92d-91001b49aae4'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=uuid.UUID('c80356c5-c30c-4aaf-8645-043246b798f0'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('618bb0eb-0ce9-4a19-910a-ffca382b2ef9'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='id',
            field=models.CharField(default=uuid.UUID('14042f15-8d31-460f-8f97-d447bf4baaf1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Id',
            field=models.CharField(default=uuid.UUID('ed903951-6dfa-4cad-a7d9-df2cbfa17261'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('ce5725cf-0c00-4900-bd4d-793fdcd703c3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='Id',
            field=models.CharField(default=uuid.UUID('93b7a075-682c-45fd-9b74-3689a5f8a2f3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=uuid.UUID('2965c76d-4e77-48ee-8121-212e106aa055'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationdriver',
            name='id',
            field=models.CharField(default=uuid.UUID('7189dbe6-82fa-4453-abbe-cae8708addda'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationfleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('04e7404b-da0d-44cc-a79b-6214763eda37'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('f358e36c-60a3-4383-b5db-640f04d7a8bc'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Id',
            field=models.CharField(default=uuid.UUID('7baba78c-8e56-47f7-a9f4-98c81c954ba3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('d2c3c8fc-96d0-471f-8514-61f631f08689'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('43e9de25-fe0d-45a9-9aef-7a5fecefd38a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.CharField(default=uuid.UUID('abdafa58-b287-412f-93e3-912332416d45'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='Id',
            field=models.CharField(default=uuid.UUID('5a2b884c-a8df-4a06-8825-fe567ac39408'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('537020e1-2142-4b84-9ab8-6d4ec931fe0b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Id',
            field=models.CharField(default=uuid.UUID('d729bb54-6598-4589-b37e-33c66c41f259'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('7788d048-77b4-4829-b7a5-2d70aec1e19f'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
