# Generated by Django 3.2.4 on 2021-06-21 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210621_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('f88f412e-6969-4e33-b468-567bc79128fd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=uuid.UUID('21caf460-a8d5-4c5a-b066-c7cd12832001'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('4a6ec049-b620-4695-9a95-fcb393e82709'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='id',
            field=models.CharField(default=uuid.UUID('9f47ac9c-fea1-4026-b879-15e996c63b16'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directoratedepartment',
            name='id',
            field=models.CharField(default=uuid.UUID('fbf75c1c-3b52-47f9-87ac-d18732186e8e'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('cd939c28-a3b9-4cef-8392-fa53a5253358'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='id',
            field=models.CharField(default=uuid.UUID('a0f7ee05-1d64-4d5b-bb8e-7eb5117af837'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanagertrip',
            name='id',
            field=models.CharField(default=uuid.UUID('649ead15-e350-4819-9a51-0b02f45c214b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=uuid.UUID('e09cf898-e11b-451e-b623-059a068b3da6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationdriver',
            name='id',
            field=models.CharField(default=uuid.UUID('215dd08b-4dfb-4420-9ee3-c3fa9e01c2e6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationfleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('27baefe4-70e3-428c-8de8-0a7bdfcffd0d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('9340bc98-56e8-4a50-95a1-2692fe08c88b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('95827a98-6e90-4606-9bdb-eb78b2691653'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengertrip',
            name='id',
            field=models.CharField(default=uuid.UUID('2a42bf42-e92b-4535-9f24-1825dbaf318f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('cd41b068-8f3c-40f7-a36f-65373c017d6c'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectvehicledeploy',
            name='id',
            field=models.CharField(default=uuid.UUID('5ecded74-0438-4119-853b-2a227a87610b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(default=uuid.UUID('610777dc-581b-44cc-878e-8a6ed8eab0c8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.CharField(default=uuid.UUID('8a25dc4a-9979-421b-8483-f78a9720edcc'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationvehicledeploy',
            name='id',
            field=models.CharField(default=uuid.UUID('5d31cb4a-f0cf-41da-b6ab-9eafda90e179'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.CharField(default=uuid.UUID('2510ca92-3a64-49d8-825c-db12f8634c62'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('33ff3dbb-36fb-486b-9da9-ac9c64227e60'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('da05d9f5-f012-4373-8277-335c705f2abb'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
