# Generated by Django 3.2.4 on 2021-09-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0011_auto_20210907_0919'),
        ('api', '0006_goat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.UUID('a365c526-2028-4985-848c-312a82699c7b'), primary_key=True, serialize=False)),
                ('expo_token', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Not sent', 'Not sent')], default='Pending', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_notification_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_notification_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerNotification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.UUID('a365c526-2028-4985-848c-312a82699c7b'), primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_passengernotification_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_passengernotification_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.passenger')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Goat',
        ),
    ]
