# Generated by Django 3.2.4 on 2021-06-21 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210621_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('4be306c6-53b2-4b62-8f21-6684cc7efda1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=uuid.UUID('f2ad4d7f-84f6-42d1-b929-daefe2212633'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('ec6c39fe-3a29-4e15-b411-b2668e47c44f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='id',
            field=models.CharField(default=uuid.UUID('1443f1e2-58cc-4d83-935e-7ae3086435a8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directoratedepartment',
            name='id',
            field=models.CharField(default=uuid.UUID('63fb9d5a-0a6e-44de-a493-930fb5083a9a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('c7ede87a-4fbd-4135-8c00-c3523298cef1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='id',
            field=models.CharField(default=uuid.UUID('0dbfa18f-368f-41a2-9f31-54320ad56639'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanagertrip',
            name='id',
            field=models.CharField(default=uuid.UUID('9bd0ca39-7ca0-48ee-b858-cf841cabfe61'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=uuid.UUID('91b3d38d-c8d3-4fa3-8a86-7e1e62a4a8c5'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationdriver',
            name='id',
            field=models.CharField(default=uuid.UUID('23d4b8a6-ae5f-4143-86f8-c81f8e2a5984'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationfleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('75095d8e-8471-42b6-8ae6-e1e028db95cf'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('3c2ec657-c109-4b16-aadf-259b7f5cb3f4'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('21279f38-4ae1-4e80-9d33-7e955d266886'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengertrip',
            name='id',
            field=models.CharField(default=uuid.UUID('25b6c185-80a3-42b4-b8d4-5c9ffd1ec5ab'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('75ca80df-f7e2-4c23-905b-8c536f09149b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectvehicledeploy',
            name='id',
            field=models.CharField(default=uuid.UUID('749c0c50-077f-4906-9180-d4ca3bcfd88f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(default=uuid.UUID('e65b66cc-b7e0-459c-a9ec-f606a88ad79f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.CharField(default=uuid.UUID('bfe377b7-feb6-4f37-ab77-54ec62bcbbe0'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationvehicledeploy',
            name='id',
            field=models.CharField(default=uuid.UUID('de85ab2d-5f61-4a26-b0ab-89b180816cef'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.CharField(default=uuid.UUID('1f2f45e2-6f7a-44dd-b004-16e72e73d00b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(default=uuid.UUID('08a7ffd3-a267-4a81-a329-8b62d9e19aff'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleblacklist',
            name='id',
            field=models.CharField(default=uuid.UUID('e5a76724-a265-4b68-86d8-c98396a2f39d'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
