# Generated by Django 3.2.4 on 2021-10-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0023_alter_passwordresetinfo_expires_at'),
        ('api', '0015_organisationpassengertrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.UUID('a365c526-2028-4985-848c-312a82699c7b'), primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_drivernotification_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.driver')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_drivernotification_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
    ]
