# Generated by Django 3.2.4 on 2021-10-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_passwordresetinfo_expires_at'),
        ('api', '0020_departmentdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpassenger',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.passenger'),
        ),
    ]
