# Generated by Django 3.2.4 on 2021-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_passwordresetinfo_expires_at'),
        ('api', '0022_alter_departmentdriver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
        ),
        migrations.AlterField(
            model_name='departmentdriver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organisationdriver'),
        ),
        migrations.AlterField(
            model_name='departmentpassenger',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organisationpassenger'),
        ),
        migrations.AlterField(
            model_name='departmentvehicle',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organisationvehicle'),
        ),
        migrations.AlterField(
            model_name='organisationvehicle',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.AlterField(
            model_name='passengerblacklist',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.passenger'),
        ),
    ]
