# Generated by Django 3.2.4 on 2021-10-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_passwordresetinfo_expires_at'),
        ('api', '0023_auto_20211025_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdriver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.driver'),
        ),
    ]
