# Generated by Django 3.2.4 on 2021-10-27 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_alter_departmentdriver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdriver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organisationdriver'),
        ),
        migrations.CreateModel(
            name='DepartmentFleetManager',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastupdated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.UUID('a365c526-2028-4985-848c-312a82699c7b'), primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_departmentfleetmanager_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('fleet_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organisationfleetmanager')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_departmentfleetmanager_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-lastupdated_at'],
                'abstract': False,
            },
        ),
    ]
