# Generated by Django 3.2.3 on 2021-05-26 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('cfe187a9-0cb0-439e-9330-0eea9d7fb3fd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('979c2092-c007-4549-8d08-7fb32cdb9c0b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('e1ba1849-2345-4321-a38f-6ba8d84b527b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('a81b3ccf-2901-4b82-a2d8-529ab9faf3e6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('89cf588f-e428-4385-aeeb-98d1fa602428'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
