# Generated by Django 2.2.1 on 2021-05-21 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('cca3b811-3821-4746-bb0d-9b414faac386'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('a695a59f-187d-4ac4-ab1e-24b4978f89dd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('897d1160-a0fa-4a29-8264-db824843554a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('4a7ab8b6-7553-4d9c-aa03-34e8b45baabc'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('8cae6b6e-cf47-42b6-ba6f-ac8c639e7d64'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
