# Generated by Django 2.2.1 on 2021-05-18 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('347119bc-3702-4820-9fda-cda7d921a5a4'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('11a0ce67-3c5f-450d-9832-b814cd559ee8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('1d784ff9-a832-494d-985f-04e387abc8af'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('56e5be4d-fe6e-4568-911e-a50193e3fb68'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('6b2a56cc-47c2-4331-833a-3771d9712aac'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
