# Generated by Django 3.2.3 on 2021-05-31 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('10fff8ee-4e37-4101-8650-de24442d1bef'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('0b719c2b-fdb9-4098-8415-7d7890e3e13e'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('e0304519-2660-4524-8042-9d59912506dc'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('23765eb6-44ab-4c4e-be61-cd21dad149f6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('e63fb1c6-ec4e-47f9-b53c-7525d6aaaba5'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
