# Generated by Django 3.2.3 on 2021-06-04 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('c73dbf76-b3f7-43af-8760-132ec4b59576'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('00b5991e-766b-46b4-9e81-6b3a7ff4bb4d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('6ab93c66-0226-4e0a-accc-551b3e455630'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('7635bbd9-f962-4b75-aa87-731b5e6ed1b2'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('bda24167-1d37-42cd-a0bb-3c9ad00952d9'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
