# Generated by Django 3.2.4 on 2021-06-07 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('669ed5a7-c1bf-4b88-b1cc-d45b193d9d12'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('d481c433-5d2f-4dde-9cb2-70d4f7b1f1ca'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('54622377-ba3d-4dc2-8fca-09dec6ccb17a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('620349b2-50d4-4e92-a0a6-ed3ff123f516'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('ce552332-3b65-48a3-bab4-ed578a206201'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
