# Generated by Django 3.2.4 on 2021-06-21 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('3ba02424-b406-4679-8ae7-cb57fa9a46de'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('250cfeb5-734b-498a-835c-d0decaf868a7'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('b8cc28fd-5220-4234-bbf7-7ef4123089b6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('a81cc646-7514-438b-9931-b354629cfe9c'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('d41f43d1-e35f-4a3c-a3d6-89a831fd6997'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
