# Generated by Django 3.2.2 on 2021-05-20 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('5545fa64-1f2e-4de9-9df6-3440dd30885b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('3c0ba536-ef17-4637-bd2b-41f9dcdb64c3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('30bc8249-f942-4c2d-b79d-5043573a958c'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('c3197652-49e2-457e-9a1d-1edadf87ebb7'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('92d3dfca-ee14-482d-a642-089bc5dd5176'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
