# Generated by Django 3.2.3 on 2021-05-27 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('a9c44cb6-6356-4411-8477-5f8444a74d08'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('ae8679cb-17e3-4939-891c-6df746976cbb'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('6798b700-6bf7-4641-8af9-0771b1953ce2'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('0ec83290-ed1f-4de0-ba39-1b7775fda869'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('69037fa6-32ad-476a-b5c1-bb6249beca4e'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
