# Generated by Django 3.2.4 on 2021-06-21 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('8df71970-26ab-4a59-b72b-61a731719fc5'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('50110603-d109-4fcd-98e6-2e70d04f4b0b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('6b90dd9e-1de9-41fb-ba9d-52bca9430984'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('a064719f-3242-4b66-9225-03161ef26f27'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('bad54657-814c-4455-b219-33549d9b204d'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
