# Generated by Django 3.2.3 on 2021-05-31 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210531_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('08a9c562-28a5-492c-a9e2-ee90c36405c8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('7c7272c7-eb02-4094-a698-25d454435105'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('3d5f0d50-36e1-42ee-a72e-90299a7545ad'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('2581962f-4b23-4348-8a35-3c34349a0975'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('36cb6876-2889-4fcd-bd15-a8f982bf2c51'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
