# Generated by Django 2.2.23 on 2021-05-18 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210518_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('d7845430-b309-44f4-a03a-ad2dd0423087'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('3513541e-ee58-460c-a294-f138d2622b71'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('06a4afe8-5d26-4075-9fc7-c5a4d12f2806'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('78f12c2e-79ce-4978-af53-297fb4a0460f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('a4f6ff5a-0e3f-41ae-8800-d36e2f1ef085'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
