# Generated by Django 3.2.4 on 2021-06-21 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210621_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('da745348-6d50-4897-87d7-945a3f0550da'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('26ba1663-2018-4cb9-a805-455f82df287b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('5915248f-7f95-4dfa-ae82-b73d5536a258'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('10e0ead3-66b9-450c-a98b-bde32b814af3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('74f4be96-49fe-48e3-a80d-efa619b530aa'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
