# Generated by Django 3.2.4 on 2021-06-07 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210607_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('cd1c81df-5f75-4a95-9f40-9f0e6dfbb78f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('3b2601ee-094d-4faf-b77c-bda1ef8154eb'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('38702fb9-203e-4326-b183-216ca6b20f52'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('e3f33f6b-5886-452b-adc0-2cb483530c84'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('5fb7ec93-3bc3-4f1b-8a97-edc7b259ee07'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
