# Generated by Django 3.2.4 on 2021-06-21 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210621_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('05b9cd5f-7ff4-489a-8854-0b35961b10a7'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('aba3f727-66dd-4b07-8625-e3120ff4b571'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('a9d8570c-6f0f-4c04-bd04-d8da0399fcdf'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('0f9a1959-0415-4b1e-b722-e52ef57631d6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('ce607119-b636-4bb4-9a94-dcfd561d3d4a'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
