# Generated by Django 3.2.3 on 2021-05-26 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210526_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('a9eec8b7-2148-4aa8-8c2c-41817ec53e07'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('73f57096-3d91-4854-acbf-62921d8d0631'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('b23375e2-b387-4739-9cd2-d5621126a1b3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('73b0cebe-92ea-4e7a-8342-b333814fccac'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('b8e9c67c-6eb2-4d87-986f-4df10b036aab'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
