# Generated by Django 3.2.4 on 2021-06-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210604_0637'),
        ('authentication', '0003_auto_20210607_0848'),
    ]

    operations = [
    ]
