# Generated by Django 3.2.3 on 2021-05-31 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210531_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('35ec0971-638a-458c-bd50-312097e35877'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('778dbf89-03a5-40ec-b873-112ee4e79699'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('1c4bd047-e3bb-4b82-9aae-7f19ac36d38b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('4b8c9200-01dc-45b0-9d4a-3cd250b72dfd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('5ee3efc7-5ebd-4963-ad48-28f88231b762'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
