# Generated by Django 3.2.3 on 2021-05-27 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210527_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('df2c9d2d-758f-4e8d-908a-5449166a1430'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('e5eb5dc8-ded0-482e-bb93-8c961b730e1c'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('50b098fd-d3ce-4a2a-9923-27b172a387d1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('ff827904-ea4d-4b7a-bd71-063264119379'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('09712c8a-cbdf-40c1-a509-8706830f7e59'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
