# Generated by Django 3.2.3 on 2021-05-19 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210518_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('797367d3-dce0-42d3-99c5-bdab886b7a6b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('3ccdffff-a3af-4418-a1c0-f40b0987c803'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('3810d986-e852-4fd6-b25f-d2000ca4615f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('0f697fdb-41c5-4166-ae5e-41d6ba358cf3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('12849c54-09d8-4528-a74b-b8660708b03b'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
