# Generated by Django 3.2.4 on 2021-06-21 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210621_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('81361036-d5c9-4ab9-96c3-49fc47522e7a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('f7dcae29-d0f1-4e1d-9071-d819d1dc21bd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('19d7e0f7-a7c1-4785-975c-bc3c5dceab66'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('9cdd0c30-aab2-4b6b-8594-588aa46da8a5'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('847df205-a1b0-4a3d-9d71-fdc33ef920ca'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
