# Generated by Django 3.2.3 on 2021-05-27 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210526_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('13697f4e-8ea7-42ee-9e49-28abc29ea4be'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('e483b303-b770-4d28-8190-fa436e09b895'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('0d180ed0-36d4-42c8-8122-a02dba581601'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('797f8639-ae48-47f0-8af1-89afa9206af6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('103152c3-802f-4f90-b83a-f13fe24d10c1'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
