# Generated by Django 3.2.3 on 2021-05-27 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210527_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('b78669ad-7841-4950-b9ca-f771a1c63aa7'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('d60a8d9a-6919-4b36-aed5-95c5b1090b38'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('420566b7-8045-4a10-9703-db6e47b45e46'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('ad339087-40c0-4981-aece-52e4a8cf5573'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('b7f8376f-cf89-4623-9d61-8bb2dfa912fe'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
