# Generated by Django 3.2.4 on 2021-06-21 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210621_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('3fdb07fb-ff82-4032-b9b0-cdbdbf60a447'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('de41b6e7-eb89-4b47-a554-141ee5567a0a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('f8697895-17c6-43a4-90cf-c6b5b0ce869d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('a04fd978-b33f-4306-9d6f-8e078a7998b3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('d9f65c65-bbae-4116-bc84-55e3f891c552'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
