# Generated by Django 3.2.2 on 2021-06-02 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210602_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('998dc98e-9e00-42fe-9bec-a9d7647f9750'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('c68cef05-e7db-4ee5-b900-fee8345a0b93'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('cb6bb8b6-634c-4c2d-945c-a022b2834d54'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('b86a28eb-d1a1-4ede-9e5c-077c79cd28bf'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('9a91f608-6d3e-404b-960a-6864c60e048c'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
