# Generated by Django 3.2.3 on 2021-05-27 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210527_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('1e8a6cdc-b8b9-47a9-85b0-aa5f0394024a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('d921183f-454b-4b0c-8563-a20db86dcc62'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('36d057c1-86bf-4619-978e-6c91ac05b42d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('fbc827a0-71ba-4fa2-b3df-caa9356733ed'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('0d8e0cec-721e-449b-b889-e9178a1023b7'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
