# Generated by Django 3.2.3 on 2021-05-28 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210527_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('528f54c6-a6db-4d84-b455-d016c192f2f4'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('14689ea8-4ee9-45b1-8aac-f09651921467'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('ee11bcfb-ea00-4bd8-85fe-01598e2e475f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('1168ee42-757d-4079-9650-b2615c93e165'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('f67f9d38-f511-40b9-bc29-c3e7fdcfad03'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
