# Generated by Django 3.2.3 on 2021-05-28 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210528_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('46fd67a9-de2a-4001-9b80-8b2bc05513a3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('fed568b3-5de1-4632-ac5f-671efddd1fd8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('4c10d1a9-0b2f-4a90-bbda-eeca65c05715'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('949cd1fd-b977-493f-ad03-a7c0c080e7e7'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('38d53b8e-e663-47dd-a464-7510a4214407'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
