# Generated by Django 3.2.3 on 2021-05-28 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210528_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('309c36e5-0081-46ec-9719-e15dfc0d7f34'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetmanager',
            name='id',
            field=models.CharField(default=uuid.UUID('8d6fe29d-4aa3-4538-9213-7640bd322fbd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.CharField(default=uuid.UUID('71d65f51-d954-4983-a85d-5de705fa1fa0'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='id',
            field=models.CharField(default=uuid.UUID('b362ec5f-7c19-4bbd-85e5-759eeeb00c3c'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.CharField(default=uuid.UUID('89a92bba-a117-4334-94f2-3ea899ada351'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
