# Generated by Django 3.2.4 on 2021-09-21 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210921_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 42, 5, 165718, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
