# Generated by Django 3.2.4 on 2021-09-21 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20210921_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 11, 30, 25, 788149, tzinfo=utc)),
        ),
    ]
