# Generated by Django 3.2.4 on 2021-09-22 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20210921_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 7, 57, 24, 509099, tzinfo=utc)),
        ),
    ]
