# Generated by Django 3.2.4 on 2021-09-27 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20210924_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 19, 54, 769125, tzinfo=utc)),
        ),
    ]
