import api._views.vehicle_views as vehicle_views
import api._views.organisation as organisation_views
import api._views.organisation_fleet_manager as organisation_fleet_manager_views
import api._views.organisation_driver as organisation_driver_views
import api._views.organisation_vehicle as organisation_vehicle_views
import api._views.project as project_views
import api._views.branch as branch_views
import api._views.station as station_views
import api._views.department as department_views
import api._views.directorate as directorate_views
import api._views.blacklist as blacklist_views
import api._views.passenger_blacklist as passenger_blacklist_views
import api._views.driver_blacklist as driver_blacklist_views
import api._views.vehicle_blacklist as vehicle_blacklist_views
